---
- name: Install
  community.general.pkgng:
    name: bastille git-lite
    state: present
    cached: "{{ bastille_pkg_cached }}"

- name: Configuration
  ansible.builtin.template:
    src: usr/local/etc/bastille/bastille.conf.j2
    dest: /usr/local/etc/bastille/bastille.conf

- name: Bastillefile base
  ansible.builtin.template:
    src: Bastillefile-base
    dest: /usr/local/bastille/templates/default/base/Bastillefile

- name: NAT64 resolv.conf for jails
  ansible.builtin.template:
    src: nat64-resolv.conf
    dest: /usr/local/bastille/templates/default/base/resolv.conf

- name: Enable service
  community.general.sysrc:
    name: bastille_enable
    value: "YES"

- name: Bootstrap releases
  ansible.builtin.command:
    cmd: "bastille bootstrap {{ item }} update"
    creates: "{{ bastille_prefix }}/releases/{{ item }}/COPYRIGHT"
  loop: "{{ bastille_releases }}"

- name: Bootstrap templates
  ansible.builtin.command:
    cmd: "bastille bootstrap {{ item }}"
  loop: "{{ bastille_templates }}"
  when: bastille_templates is defined

- name: Create jails
  ansible.builtin.command:
    cmd: bastille create {{ item.name }} {{ item.release }} {{ item.ip }} {{ item.interface }}
    creates: "{{ bastille_prefix }}/jails/{{ item.name }}/root/COPYRIGHT"
  loop: "{{ bastille_jails }}"
  when: bastille_jails is defined

- name: Apply templates
  ansible.builtin.command:
    cmd: "bastille template {{ item.0.name }} {{ item.1 }}"
  with_subelements:
    - "{{ bastille_jails }}"
    - templates
    - skip_missing: yes
  when: bastille_jails is defined
