#!/bin/sh

# PROVIDE: {{ generic_service_name }}
# REQUIRE: LOGIN DAEMON NETWORKING
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable {{ generic_service_name }}
# {{ generic_service_name }}_enable="YES"

. /etc/rc.subr

name="{{ generic_service_name }}"
rcvar="{{ generic_service_name }}_enable"

command="/usr/sbin/daemon"
pidfile="{{ generic_service_pidfile_directory }}/${name}.pid"
daemon_pidfile="{{ generic_service_pidfile_directory }}/daemon.pid"

task="{{ generic_service_command }}"
procname="{{ generic_service_procname }}"

{{ generic_service_name }}_chdir="{{ generic_service_content_directory }}"

command_args="-p ${pidfile} -P ${daemon_pidfile} -t ${name} -u {{ generic_service_user }} -H -o {{ generic_service_log_file }} ${task}"

load_rc_config $name
run_rc_command "$1"
