---
- name: Create dataset
  community.general.zfs:
    name: zroot/jails
    state: present
    extra_zfs_properties:
      mountpoint: /usr/local/jails

- name: Enable
  community.general.sysrc:
    name: "jail_enable"
    value: "YES"

- name: Fix IPv6 issue
  # Services in jails cannot bind to IPv6 addresses on boot for some reason
  # https://forums.freebsd.org/threads/52096/
  ansible.posix.sysctl:
    name: net.inet6.ip6.dad_count
    value: '0'

- name: Include tasks to build template jail
  ansible.builtin.include_tasks:
    file: build_template.yml

- name: Include tasks to provision jails
  ansible.builtin.include_tasks:
    file: provision_jails.yml

- name: Include tasks to remove jails
  ansible.builtin.include_tasks:
    file: remove_jails.yml

- name: Populate configuration file
  ansible.builtin.template:
    src: jail.conf
    dest: /etc/jail.conf
  notify:
    - restart jails

- name: Start
  ansible.builtin.service:
    name: jail
    state: started
