---
- name: Install
  community.general.pkgng:
    name: postgresql14-server
    state: present

- name: Create data directory
  ansible.builtin.command:
    cmd: pg_ctl initdb -D /var/db/postgres/data14
    creates: /var/db/postgres/data14
  become: true
  become_user: postgres

- name: Configure pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /var/db/postgres/data14/pg_hba.conf
    mode: "0600"

- name: Enable
  community.general.sysrc:
    name: postgresql_enable
    value: "YES"

- name: Start
  ansible.builtin.service:
    name: postgresql
    state: started
