---
- name: Install package
  community.general.pkgng:
    name: nomad nomad-pot-driver
    state: present

- name: Create data pool
  community.general.zfs:
    name: "{{ nomad_zfs_pool }}{{ nomad_data_directory }}"
    state: present

- name: Fix nomad data directory permissions
  ansible.builtin.file:
    path: "{{ nomad_data_directory }}"
    owner: nomad
    group: nomad
    mode: '0700'

- name: Set nomad_dir
  community.general.sysrc:
    name: nomad_dir
    value: "{{ nomad_data_directory }}"

- name: Enable service
  community.general.sysrc:
    name: nomad_enable
    value: "YES"

- name: Find all files in configuration directory
  ansible.builtin.find:
    paths: "{{ nomad_config_directory }}"
    patterns: '^(?!server.hcl).*$'
    use_regex: true
  register: configuration
  ignore_errors: true

- name: Cleanup previously found files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ configuration.files }}"
  ignore_errors: true

- name: rc script
  ansible.builtin.template:
    src: rc
    dest: "{{ nomad_rc_file }}"
    mode: 0755
    owner: root
    group: wheel
  notify:
    - restart nomad

- name: Configuration file
  ansible.builtin.template:
    src: server.hcl
    dest: "{{ nomad_config_file }}"
    mode: 0750
    owner: nomad
    group: nomad
  notify:
    - restart nomad

- name: Start service
  ansible.builtin.service:
    name: nomad
    state: started
