---

- name: Create jails
  ansible.builtin.command:
    cmd: ezjail-admin create -f {{ item.flavour }} {{ item.name }} {{ item.ip_configuration }}
    creates: /usr/jails/{{ item.name }}
  loop: "{{ ezjail_create }}"
  when: ezjail_create is defined

- name: Start jails
  ansible.builtin.service:
    name: ezjail
    args: "{{ item.name }}"
    state: started
  loop: "{{ ezjail_create }}"
  when: ezjail_create is defined

- name: Install python3 into jails
  community.general.pkgng:
    state: present
    name: python3
    jail: "{{ item.name }}"
  loop: "{{ ezjail_create }}"
  when: ezjail_create is defined
