---
- name: Install
  community.general.pkgng:
    name: acme.sh
    state: present

- name: Create newsyslog configuration
  ansible.builtin.template:
    src: acme.sh.conf
    dest: /usr/local/etc/newsyslog.conf.d/acme.sh.conf
    mode: "0640"
    owner: root
    group: wheel

- name: Create account.conf
  ansible.builtin.template:
    src: account.conf
    dest: /var/db/acme/.acme.sh/account.conf
    mode: "0640"
    owner: acme
    group: acme

# This file needs to be created to register an account.
- name: Create log file
  ansible.builtin.file:
    path: "{{ acmesh_logfile }}"
    state: touch
    mode: "0600"
    owner: acme
    group: acme

# Group is www for haproxy to read the certs
- name: Create directory for certificates
  ansible.builtin.file:
    path: /usr/local/etc/ssl/acme.sh
    state: directory
    owner: acme
    group: www
    mode: "0750"

- name: Create renew cronjob
  ansible.builtin.cron:
    name: Renew certificates
    user: acme
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "{{ 23 | random(seed=inventory_hostname) }}"
    job: acme.sh --cron --home /var/db/acme/.acme.sh
