---

- name: Copy ipv6-only flavour
  ansible.builtin.copy:
    src: /usr/jails/flavours/example/
    dest: /usr/jails/flavours/ipv6-only
    remote_src: yes
    force: no

- name: Copy authorized_keys to jail flavour
  ansible.builtin.copy:
    src: /root/.ssh
    dest: /usr/jails/flavours/ipv6-only/root
    remote_src: yes
    force: no

- name: Enable sshd in ipv6-only jails
  community.general.sysrc:
    name: "sshd_enable"
    value: "YES"
    path: /usr/jails/flavours/ipv6-only/etc/rc.conf

- name: Allow root login via ssh to ipv6-only jails
  community.general.sysrc:
    name: "sshd_flags"
    value: "-o PermitRootLogin=prohibit-password"
    path: /usr/jails/flavours/ipv6-only/etc/rc.conf

- name: NAT64 resolv.conf for ipv6-only jails
  ansible.builtin.template:
    src: ipv6-only-resolv.conf
    dest: /usr/jails/flavours/ipv6-only/etc/resolv.conf
