---
- name: Install
  community.general.pkgng:
    name: haproxy
    state: present

- name: Create syslog configuration
  ansible.builtin.template:
    src: syslog
    dest: /usr/local/etc/syslog.d/haproxy.conf
    mode: 0644

- name: Configure syslog to allow remote logs
  community.general.sysrc:
    name: syslogd_flags
    value: ""

# This is too generic and should probably be somewhere else
- name: Create directory newsyslog
  ansible.builtin.file:
    path: /usr/local/etc/newsyslog.conf.d
    state: directory
    owner: root
    group: wheel
    mode: 0644

- name: Create newsyslog configuration
  ansible.builtin.template:
    src: newsyslog
    dest: /usr/local/etc/newsyslog.conf.d/haproxy.conf
    mode: 0644

- name: Create haproxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /usr/local/etc/haproxy.conf
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: reload haproxy

- name: Enable service
  community.general.sysrc:
    name: haproxy_enable
    value: "YES"

- name: Start service
  ansible.builtin.service:
    name: haproxy
    state: started
