---
- name: Install
  community.general.pkgng:
    name: haproxy
    state: present

- name: Create syslog configuration file
  ansible.builtin.template:
    src: syslog
    dest: /usr/local/etc/syslog.d/haproxy.conf
    mode: 0644

- name: Configure syslog to allow remote logs
  community.general.sysrc:
    name: syslogd_flags
    value: ""

- name: Create haproxy configuration file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /usr/local/etc/haproxy.conf
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Enable service
  community.general.sysrc:
    name: haproxy_enable
    value: "YES"

- name: Start service
  ansible.builtin.service:
    name: haproxy
    state: started
