---
- name: Install
  community.general.pkgng:
    name: ezjail
    state: present
    # cached: False is too slow
    cached: True

- name: Enable
  community.general.sysrc:
    name: "ezjail_enable"
    value: "YES"

- name: Create loopback interface
  community.general.sysrc:
    name: "cloned_interfaces"
    value: "lo1"

- name: Start loopback interface
  ansible.builtin.command:
    cmd: service netif cloneup

- name: Populate basejail with -RELEASE
  ansible.builtin.command:
    cmd: ezjail-admin install -p
    creates: /usr/jails/basejail/usr

- name: Copy example flavour to ipv6-only
  ansible.builtin.copy:
    src: /usr/jails/flavours/example
    dest: /usr/jails/flavours/ipv6-only
    remote_src: yes
    force: no

- name: NAT64 resolv.conf for jails
  ansible.builtin.template:
    src: ipv6-only-resolv.conf
    dest: /usr/jails/flavours/ipv6-only/etc/resolv.conf
